services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
      #ports:
      #- "5432:5432"
    restart: always
    environment:
      #POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      #POSTGRES_DB: postgres

  adminer:
    image: adminer
    ports:
      - "8083:8080"

  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db

